import type { NextPage } from 'next';
import Head from 'next/head';
import { VStack } from '@chakra-ui/react';
import PageWrapper from '../components/PageWrapper';
import MainPageHero from '../components/homepage/hero';

const Home: NextPage = () => {
  return (
    <>
      <PageWrapper>
        <Head>
          <title>Foodit - Your online food plug</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        {/* Main contents start here */}
        <VStack mx='auto !important'>
          <MainPageHero />
        </VStack>
      </PageWrapper>
    </>
  );
};

export default Home;
